// Package plan — query-binding inference and seed-rule generation for magic sets.
//
// The MagicSetTransform itself only knows how to *propagate* bindings through
// rule bodies once told which top-level head positions are bound. Production
// queries need two extra pieces:
//
//  1. **Binding inference.** Walk the desugared query body and figure out which
//     argument positions of each IDB-predicate literal are bound at query time.
//     A position is bound if its term is a constant, a wildcard variable equated
//     to a constant by a `=` comparison in the same query body, or a variable
//     that is already bound by a preceding base-relation literal carrying a
//     constant in the corresponding column.
//
//  2. **Seed rules.** The magic_<pred>(...) propagation rules generated by the
//     transform have no base case unless the EDB is seeded. We generate a seed
//     rule for each query body literal of the form
//     magic_<pred>(args_at_bound_positions) :- <preceding query body lits>.
//     The preceding-literal context is what gives us the bound values at runtime.
//
// Conservative-by-design: if we cannot determine that a position is bound,
// we omit it from the binding set. An empty binding set causes WithMagicSet
// to fall through to plain Plan, which is the safe baseline.
package plan

import (
	"fmt"

	"github.com/Gjdoalfnrxu/tsq/ql/datalog"
)

// QueryBindingInference is the result of analysing a query body.
type QueryBindingInference struct {
	// Bindings maps IDB predicate name → bound argument positions, as
	// expected by MagicSetTransform.
	Bindings map[string][]int
	// SeedRules are zero- or N-body rules that derive magic_<pred> facts at
	// evaluation time using the query body's own context.
	SeedRules []datalog.Rule
	// Fallback is true if WithMagicSetAuto inferred bindings but the
	// augmented (magic-rewritten + seeded) program failed to plan, causing
	// a silent fallback to plain Plan(prog). Distinguishes "no bindings to
	// infer" (Fallback=false, Bindings=nil) from "bindings inferred but the
	// transform produced an unplannable program" (Fallback=true,
	// Bindings=nil). See issue #112.
	Fallback bool
	// FallbackReason carries the first planning error returned by the
	// augmented program when Fallback is true. nil otherwise.
	FallbackReason error
}

// MagicSetOptions controls WithMagicSetAutoOpts behaviour.
//
// Strict, when true, suppresses the silent fallback: if the augmented
// program fails to plan, the planning errors are returned to the caller
// rather than being swallowed in favour of plain Plan(prog). Use this in
// tests and CI to detect transform regressions that would otherwise be
// invisible (issue #112). Default (zero value) preserves the historical
// silent-fallback behaviour for production use.
type MagicSetOptions struct {
	Strict bool
}

// InferQueryBindings analyses prog.Query and returns the binding map and the
// seed rules needed to make the magic-set rewrite produce results.
//
// idbPreds is the set of predicate names that appear as rule heads in the
// program (i.e. derived predicates eligible for magic-set rewriting).
//
// Returns an empty inference (nil maps/slices) if the query has no body or
// no inferable bindings — caller should then skip the magic-set transform.
func InferQueryBindings(prog *datalog.Program, idbPreds map[string]bool) QueryBindingInference {
	if prog == nil || prog.Query == nil || len(prog.Query.Body) == 0 {
		return QueryBindingInference{}
	}

	// First pass: collect variables that are equality-constrained to constants
	// in the query body. These are "bound by query" — when their host literal
	// is evaluated, the variable will have a known value.
	constBoundVars := make(map[string]bool)
	varToConst := make(map[string]datalog.Term)
	for _, lit := range prog.Query.Body {
		if lit.Cmp == nil || lit.Cmp.Op != "=" {
			continue
		}
		// var = const  or  const = var
		if v, ok := lit.Cmp.Left.(datalog.Var); ok {
			if isConstTerm(lit.Cmp.Right) {
				constBoundVars[v.Name] = true
				varToConst[v.Name] = lit.Cmp.Right
			}
		}
		if v, ok := lit.Cmp.Right.(datalog.Var); ok {
			if isConstTerm(lit.Cmp.Left) {
				constBoundVars[v.Name] = true
				varToConst[v.Name] = lit.Cmp.Left
			}
		}
	}

	// Second pass: track variables bound by *preceding* base-relation
	// (non-IDB) literals. Positional binding from preceding IDB literals is
	// NOT used because (a) it is almost always trivially true (any second IDB
	// literal sharing a var with the first has a "bound" first column), which
	// makes magic-set rewriting fire on queries it does not actually help, and
	// (b) it can introduce IDB→IDB seed-rule dependencies that perturb
	// stratification. v1 restricts itself to true ground-by-query bindings:
	//   - constant terms in the IDB literal itself,
	//   - vars equality-constrained to a constant in the query body,
	//   - vars ground by a preceding base-relation atom that itself contains
	//     a constant in the same column (proxy: the variable shares an atom
	//     with a constant in a preceding base literal).
	baseBoundVars := make(map[string]bool)

	bindings := make(map[string][]int)
	var seedRules []datalog.Rule

	for i, lit := range prog.Query.Body {
		// Skip non-positive / comparison / aggregate literals — they don't
		// contribute new IDB-position bindings.
		if lit.Cmp != nil || lit.Agg != nil || !lit.Positive {
			continue
		}
		pred := lit.Atom.Predicate
		if !idbPreds[pred] {
			// Not an IDB pred — it can ground variables for subsequent literals,
			// but only those vars that co-occur with a constant in this base
			// atom (i.e. the atom acts as a constant-bound lookup). This keeps
			// the inference conservative: a free base atom over a variable
			// alone does not "bind" anything in the magic-set sense.
			if hasConstTerm(lit.Atom.Args) {
				for _, arg := range lit.Atom.Args {
					if v, ok := arg.(datalog.Var); ok && v.Name != "_" {
						baseBoundVars[v.Name] = true
					}
				}
			}
			continue
		}

		// Determine which argument positions of this IDB literal are bound at
		// query-evaluation time. A position is bound if:
		//   - it's a constant term, OR
		//   - it's a variable that's in constBoundVars (= const constraint), OR
		//   - it's a variable that's positionally-bound by a preceding literal.
		var boundCols []int
		for ai, arg := range lit.Atom.Args {
			switch a := arg.(type) {
			case datalog.IntConst, datalog.StringConst:
				boundCols = append(boundCols, ai)
			case datalog.Var:
				if a.Name == "_" {
					continue
				}
				if constBoundVars[a.Name] || baseBoundVars[a.Name] {
					boundCols = append(boundCols, ai)
				}
			}
		}

		if len(boundCols) > 0 {
			// Merge with existing bindings for this predicate. v1 takes the
			// first occurrence's bindings (a conservative non-intersect choice).
			// If the same pred recurs with a different binding shape we keep
			// the first; the equivalence tests guarantee correctness either way.
			if _, exists := bindings[pred]; !exists {
				bindings[pred] = boundCols
			}

			// Build the seed rule:
			//   magic_<pred>(args_at_bound_positions) :- <preceding query body literals>.
			// "Preceding" means literals 0..i-1 — they provide the binding
			// context (constraints + base lookups) needed to ground the bound vars.
			seedHeadArgs := make([]datalog.Term, len(boundCols))
			for k, col := range boundCols {
				arg := lit.Atom.Args[col]
				// If the arg is a variable that has a known constant value
				// (via `var = const` in the query body), substitute the
				// constant directly. This lets us emit a fact-shaped seed
				// (no body needed for that var) instead of relying on the
				// evaluator to derive the binding from a bare comparison.
				if v, ok := arg.(datalog.Var); ok {
					if c, has := varToConst[v.Name]; has {
						arg = c
					}
				}
				seedHeadArgs[k] = arg
			}
			seedHead := datalog.Atom{
				Predicate: magicName(pred),
				Args:      seedHeadArgs,
			}
			// Body = all preceding query literals (j < i). Trailing
			// `var = const` comparisons are unnecessary because the constant
			// has already been substituted into the seed head above.
			// Aggregates are skipped — they can't appear at this scope cleanly.
			var seedBody []datalog.Literal
			for j, prev := range prog.Query.Body {
				if j >= i || prev.Agg != nil {
					continue
				}
				seedBody = append(seedBody, prev)
			}

			// Safety check: every variable in the seed head must appear in
			// the seed body (or be a constant). isSafe handles that.
			if isSafe(seedHead, seedBody) {
				seedRules = append(seedRules, datalog.Rule{
					Head: seedHead,
					Body: seedBody,
				})
			} else {
				// Couldn't generate a safe seed — drop the binding to avoid
				// rewriting a rule whose magic predicate will never have any
				// tuples (which would yield an empty result set).
				delete(bindings, pred)
			}
		}

	}

	if len(bindings) == 0 {
		return QueryBindingInference{}
	}
	return QueryBindingInference{
		Bindings:  bindings,
		SeedRules: seedRules,
	}
}

// InferRuleBindings extends magic-set binding inference across rule
// boundaries (issue #121, Phase A).
//
// `InferQueryBindings` only walks the *query* body. That misses the
// load-bearing case behind issue #121: a Configuration-class query
// (BackwardTracker pattern) selects a small `hasFlowTo(_, _)` IDB whose
// body itself contains a tiny IDB literal (`isSink`) followed by a large
// recursive predicate (`flowsTo`). The query body has no constants, so
// `InferQueryBindings` returns nothing and magic-set never fires —
// exactly the case where it would help most.
//
// `InferRuleBindings` complements this by walking *rule* bodies. For
// each rule it identifies "small-IDB-bound" body literals: positive
// IDB literals whose source predicate's known cardinality (via
// `sizeHints`, populated by the trivial-IDB pre-pass) is below
// `smallIDBThreshold`. Variables appearing in such a literal are then
// treated as bound for the purposes of binding inference on subsequent
// IDB literals in the same rule body. The output is a per-predicate
// map of bound argument positions, suitable for merging into the
// `queryBindings` map consumed by `MagicSetTransform`.
//
// The conservatism of `InferQueryBindings` carries through: only the
// *first* rule body that produces a binding for a given predicate is
// recorded (subsequent shapes are ignored), and we never bind through
// a literal we cannot ground.
//
// Returns nil if no cross-rule bindings are inferable, in which case
// the caller proceeds with query-body-only bindings.
func InferRuleBindings(prog *datalog.Program, idbPreds map[string]bool, sizeHints map[string]int) map[string][]int {
	if prog == nil || len(prog.Rules) == 0 {
		return nil
	}
	bindings := make(map[string][]int)

	for _, rule := range prog.Rules {
		// Track variables already grounded by a prior body literal whose
		// source IDB is small enough to seed binding inference.
		bound := make(map[string]bool)
		// Track whether we've seen a "small IDB" literal in this rule
		// body. We only emit rule bindings AFTER such a literal has
		// fired — otherwise every transitive-closure rule with a
		// preceding base atom (e.g. `Path(x,z) :- Edge(x,y), Path(y,z)`)
		// would record a binding for `Path` and trigger magic-set
		// rewriting on queries that have no constants and would not
		// benefit. The whole point of issue #121 is to make
		// Configuration-shaped queries (small IDB sink → large IDB
		// flow) bindable; non-Configuration shapes must remain
		// unaffected.
		smallIDBSeen := false

		// Head args are bound from the perspective of *callers* of the
		// rule, but for cross-rule binding within the rule body itself we
		// only care about how body literals constrain each other. Head
		// args appearing in the body would naturally be ground by the
		// body's own positive literals, so we don't seed `bound` from the
		// head.

		for _, lit := range rule.Body {
			if lit.Cmp != nil || lit.Agg != nil {
				continue
			}
			if !lit.Positive {
				// Negated literal: contributes vars to the unbound set
				// only if every var was already bound (it then acts as a
				// filter). It cannot itself bind a fresh variable, so
				// skip.
				continue
			}

			pred := lit.Atom.Predicate

			// Determine which positions of THIS literal are already bound
			// by prior small-IDB or constant binding. If at least one
			// position is bound AND a preceding small IDB (or query-time
			// constant in this same body) has fired, record it for this
			// predicate (first-occurrence wins, mirroring
			// InferQueryBindings). Without the smallIDBSeen gate, every
			// transitive-closure rule body would record a "false-positive"
			// binding the moment any base literal preceded the recursive
			// call — see TestInferRuleBindings_NoMagicWhenSourceAndSinkBothLarge
			// for the regression guard.
			if idbPreds[pred] && smallIDBSeen {
				var boundCols []int
				for ai, arg := range lit.Atom.Args {
					switch a := arg.(type) {
					case datalog.IntConst, datalog.StringConst:
						boundCols = append(boundCols, ai)
					case datalog.Var:
						if a.Name == "_" {
							continue
						}
						if bound[a.Name] {
							boundCols = append(boundCols, ai)
						}
					}
				}
				if len(boundCols) > 0 {
					if _, exists := bindings[pred]; !exists {
						bindings[pred] = boundCols
					}
				}
			}

			// Decide whether THIS literal grounds its variables for
			// subsequent literals. Two cases:
			//
			// 1. Non-IDB (base relation) literal: always grounds its vars
			//    once it produces a tuple — same conservative rule used
			//    inside InferQueryBindings (`baseBoundVars`).
			// 2. IDB literal: only grounds its vars if its predicate is
			//    "small" — meaning sizeHints reports a cardinality below
			//    smallIDBThreshold, OR no hint exists but the literal
			//    contains a constant arg (treated as inherently selective).
			//    Without this gate, every IDB literal would seed binding
			//    for every subsequent literal, which collapses to the
			//    trivial "every position is always bound" case the
			//    InferQueryBindings docstring explicitly warns against.
			grounding := false
			groundedBySmallIDB := false
			if !idbPreds[pred] {
				// Base relations ground their vars but DO NOT count as
				// "small IDB" — they're EDB. This is the key distinction:
				// only a derived (IDB) predicate whose cardinality is
				// known small triggers the rule-binding gate. Without
				// this, every rule body with a constant base literal
				// (common in system rules — e.g.
				// ImportBinding(sym, "react", "useState")) would fire
				// rule-binding inference on the next IDB literal,
				// regressing magic-set behaviour for non-Configuration
				// queries.
				grounding = true
			} else if sizeHints != nil {
				if hint, ok := sizeHints[pred]; ok && hint > 0 && hint <= smallIDBThreshold {
					grounding = true
					groundedBySmallIDB = true
				}
			}
			if !grounding {
				continue
			}
			if groundedBySmallIDB {
				smallIDBSeen = true
			}
			for _, arg := range lit.Atom.Args {
				if v, ok := arg.(datalog.Var); ok && v.Name != "_" {
					bound[v.Name] = true
				}
			}
		}
	}

	if len(bindings) == 0 {
		return nil
	}
	return bindings
}

// BuildRuleSeedRules emits `magic_<bodyPred>(args)` seed rules sourced
// from small-IDB literals in rule bodies (issue #121).
//
// Given `bindings` from `InferRuleBindings`, walks each rule body and,
// for any IDB literal whose predicate is in `bindings`, emits a seed
// rule of the shape:
//
//	magic_<pred>(args_at_bound_positions) :- <preceding small-IDB or base literals>.
//
// "Preceding" includes only literals that we know to be grounding under
// the same heuristic used in `InferRuleBindings` — base relations,
// small IDBs, or literals containing a constant arg. This keeps the
// seed rule itself tractable (no propagation through `flowsTo` in the
// seed body, which would re-create the OOM we are trying to avoid).
//
// The emitted seed rules are intended to be appended to the magic-set
// transformed program alongside the transform's own propagation rules.
// They give the magic predicate an EDB-shaped base case so the
// transformed `hasFlowTo` rule actually produces tuples even when the
// query head has no query-time bindings.
func BuildRuleSeedRules(prog *datalog.Program, idbPreds map[string]bool, sizeHints map[string]int, bindings map[string][]int) []datalog.Rule {
	if prog == nil || len(bindings) == 0 {
		return nil
	}
	// Track which (pred, arity) shapes we've already emitted so we don't
	// produce duplicate seed rules from multiple rule occurrences.
	seenShape := make(map[string]bool)
	shapeKey := func(head datalog.Atom) string {
		return fmt.Sprintf("%s/%d", head.Predicate, len(head.Args))
	}

	var seeds []datalog.Rule
	for _, rule := range prog.Rules {
		bound := make(map[string]bool)
		var prevGrounding []datalog.Literal
		smallIDBSeen := false

		for _, lit := range rule.Body {
			if lit.Cmp != nil || lit.Agg != nil || !lit.Positive {
				// Comparisons that bind a var to a constant ARE grounding
				// for subsequent literals; carry them along but they
				// don't contribute IDB shape themselves.
				if lit.Cmp != nil && lit.Cmp.Op == "=" {
					prevGrounding = append(prevGrounding, lit)
					if v, ok := lit.Cmp.Left.(datalog.Var); ok && isConstTerm(lit.Cmp.Right) {
						bound[v.Name] = true
					}
					if v, ok := lit.Cmp.Right.(datalog.Var); ok && isConstTerm(lit.Cmp.Left) {
						bound[v.Name] = true
					}
				}
				continue
			}
			pred := lit.Atom.Predicate

			if cols, ok := bindings[pred]; ok && smallIDBSeen {
				// Try to emit a seed rule. Build the head from the bound
				// positions, but only if every chosen var is in `bound`
				// (or is a constant in the literal itself).
				headArgs := make([]datalog.Term, 0, len(cols))
				safe := true
				for _, col := range cols {
					if col >= len(lit.Atom.Args) {
						safe = false
						break
					}
					arg := lit.Atom.Args[col]
					switch a := arg.(type) {
					case datalog.IntConst, datalog.StringConst:
						headArgs = append(headArgs, a)
					case datalog.Var:
						if a.Name == "_" || !bound[a.Name] {
							safe = false
						}
						headArgs = append(headArgs, a)
					default:
						safe = false
					}
					if !safe {
						break
					}
				}
				if safe && len(headArgs) == len(cols) {
					seedHead := datalog.Atom{
						Predicate: magicName(pred),
						Args:      headArgs,
					}
					key := shapeKey(seedHead)
					if !seenShape[key] {
						seedBody := append([]datalog.Literal(nil), prevGrounding...)
						if isSafe(seedHead, seedBody) {
							seeds = append(seeds, datalog.Rule{
								Head: seedHead,
								Body: seedBody,
							})
							seenShape[key] = true
						}
					}
				}
			}

			// Update grounding state. Grounding rule mirrors
			// InferRuleBindings: base relations, small IDBs, or const-bearing
			// literals all ground their variables for subsequent steps.
			grounding := false
			groundedBySmallIDB := false
			if !idbPreds[pred] {
				grounding = true
			} else if sizeHints != nil {
				if hint, ok := sizeHints[pred]; ok && hint > 0 && hint <= smallIDBThreshold {
					grounding = true
					groundedBySmallIDB = true
				}
			}
			if grounding {
				prevGrounding = append(prevGrounding, lit)
				if groundedBySmallIDB {
					smallIDBSeen = true
				}
				for _, arg := range lit.Atom.Args {
					if v, ok := arg.(datalog.Var); ok && v.Name != "_" {
						bound[v.Name] = true
					}
				}
			}
		}
	}
	return seeds
}

// filterRuleBindingsAvoidingWildcards removes any (pred, cols) entry
// from `bindings` for which some rule body contains a literal `pred(...)`
// with a Wildcard or `_`-Var in one of the bound positions. Such a
// binding causes MagicSetTransform's propagation pass to emit an
// unsafe `magic_<pred>(_, ...)` head, which the planner subsequently
// rejects.
//
// We could fix this in MagicSetTransform itself (filtering unsafe
// propagation heads at emit time), but that would change the
// observable behaviour of the existing fallback test suite (e.g.
// TestWithMagicSetAuto_UnsafeHeadFallback), which deliberately
// exercises the planner-level rejection. Filtering bindings up-front
// keeps the existing contract intact while still letting issue #121's
// rule-derived bindings take effect on safe predicates.
func filterRuleBindingsAvoidingWildcards(prog *datalog.Program, bindings map[string][]int) map[string][]int {
	if prog == nil || len(bindings) == 0 {
		return bindings
	}
	// Iterate to a fixed point: each pass computes the transitive
	// binding closure under the current set, identifies any closure
	// entry that intersects a wildcard-bearing body literal, drops
	// any *seed* binding whose closure includes that bad predicate,
	// and re-runs. This catches both direct wildcard collisions and
	// indirect ones reached only through propagateBindings.
	//
	// Termination: each iteration either returns (no bad preds, or
	// no progress) or strictly reduces |current|. Bound: O(|bindings|)
	// outer iterations, each O(|bindings| * propagateBindings) — fine
	// for the small binding maps Phase A produces.
	current := make(map[string][]int, len(bindings))
	for k, v := range bindings {
		current[k] = v
	}
	for {
		closure := propagateBindings(prog.Rules, current)
		bad := make(map[string]bool)
		for _, rule := range prog.Rules {
			for _, lit := range rule.Body {
				if lit.Cmp != nil || lit.Agg != nil || !lit.Positive {
					continue
				}
				cols, ok := closure[lit.Atom.Predicate]
				if !ok {
					continue
				}
				for _, col := range cols {
					if col >= len(lit.Atom.Args) {
						bad[lit.Atom.Predicate] = true
						break
					}
					switch a := lit.Atom.Args[col].(type) {
					case datalog.Wildcard:
						bad[lit.Atom.Predicate] = true
					case datalog.Var:
						if a.Name == "_" {
							bad[lit.Atom.Predicate] = true
						}
					}
					if bad[lit.Atom.Predicate] {
						break
					}
				}
			}
		}
		if len(bad) == 0 {
			return current
		}
		// Drop any current seed binding whose closure (forward
		// propagation from that seed alone) reaches a bad predicate.
		next := make(map[string][]int)
		dropped := false
		for pred, cols := range current {
			single := map[string][]int{pred: cols}
			singleClosure := propagateBindings(prog.Rules, single)
			tainted := false
			for badPred := range bad {
				if _, hit := singleClosure[badPred]; hit {
					tainted = true
					break
				}
			}
			if tainted {
				dropped = true
				continue
			}
			next[pred] = cols
		}
		if !dropped {
			// No seed binding individually reaches the bad set, yet
			// the combined closure does. Conservative bail: drop
			// everything to preserve the existing fallback contract.
			return nil
		}
		current = next
		if len(current) == 0 {
			return nil
		}
	}
}

// smallIDBThreshold is the cardinality below which an IDB literal is
// treated as "small enough to seed binding inference for subsequent
// literals in the same rule body" (issue #121).
//
// Rationale: backward-dataflow Configuration queries depend on the
// `isSink_<Subclass>` IDB being orders of magnitude smaller than the
// `flowsTo` literal it precedes. In practice these subclass IDBs hold
// dozens to low-thousands of tuples on real corpora (mastodon
// `setStateUpdaterCallsFn`: ~50 setter sinks). We pick 5000 as a
// conservative default — large enough to capture realistic sink/source
// IDBs without firing on broad helper IDBs (e.g. `isUseStateSetterCall`
// is 7 tuples, `functionContainsStar` is 438k on mastodon: clear
// separation). If a user's selectivity heuristic differs, the right
// long-term knob is per-binding cost estimation in the planner, not a
// magic constant — but for Phase A, a single threshold is enough to
// validate the approach. Tracked in the issue as a follow-up.
const smallIDBThreshold = 5000

// IDBPredicates returns the set of predicate names that appear as rule heads.
func IDBPredicates(prog *datalog.Program) map[string]bool {
	idb := make(map[string]bool)
	if prog == nil {
		return idb
	}
	for _, r := range prog.Rules {
		idb[r.Head.Predicate] = true
	}
	return idb
}

// WithMagicSetAuto infers query bindings, applies the magic-set transform
// when bindings are inferable, generates the seed rules required to make the
// magic predicates produce tuples at evaluation time, and plans the result.
//
// Returns the plan, the inference (so callers can log what fired), and any
// planning errors. If no bindings are inferable, falls back to plain Plan and
// returns an inference with empty Bindings.
//
// This is the non-strict, backwards-compatible entry point: planning errors
// from the augmented program are silently swallowed in favour of plain Plan.
// See WithMagicSetAutoOpts for strict-mode usage that surfaces those errors
// (issue #112).
func WithMagicSetAuto(prog *datalog.Program, sizeHints map[string]int) (*ExecutionPlan, QueryBindingInference, []error) {
	return WithMagicSetAutoOpts(prog, sizeHints, MagicSetOptions{})
}

// WithMagicSetAutoOpts is the configurable form of WithMagicSetAuto.
//
// When opts.Strict is false (default), behaviour is identical to
// WithMagicSetAuto: any planning error on the augmented program triggers a
// silent fallback to plain Plan, with QueryBindingInference.Fallback=true
// and .FallbackReason populated so callers can observe the regression.
//
// When opts.Strict is true, planning errors from the augmented program are
// returned to the caller rather than triggering fallback. Use this in tests
// and CI to detect transform-soundness regressions (issue #112).
func WithMagicSetAutoOpts(prog *datalog.Program, sizeHints map[string]int, opts MagicSetOptions) (*ExecutionPlan, QueryBindingInference, []error) {
	idb := IDBPredicates(prog)
	inf := InferQueryBindings(prog, idb)

	// Issue #121: in addition to query-body bindings, walk rule bodies
	// looking for small-IDB-bound IDB literals. This is what makes
	// Configuration-shaped queries (BackwardTracker pattern in
	// bridge/tsq_dataflow_track.qll) magic-set-rewritable: the query
	// body has no constants, but a rule body like
	//   hasFlowTo(s, t) :- isSink(t), isSource(s), flowsTo(s, t), ...
	// has `t` bound by the small `isSink` IDB before `flowsTo` is
	// reached, so `flowsTo`'s second argument can be backward-magic.
	// Drop IDB-shadowed entries from sizeHints before passing into
	// rule-binding inference (the resulting map keeps only base-only
	// hints — i.e. hints whose key does NOT appear as an IDB head).
	// The CLI's `sizeHints` map (built by buildSizeHints) is
	// populated from the BASE relation schema; many IDB class-predicate
	// names shadow a base relation of the same name (e.g. the `MethodCall`
	// QL class shadows the `MethodCall(this, recv, name)` base relation),
	// so a raw `sizeHints["MethodCall"]` lookup returns the BASE size, not
	// the IDB size. Treating that as a small-IDB signal would fire
	// rule-binding inference on every Configuration-shaped IDB whose name
	// happens to overlap with a small base — a soundness regression
	// (TestCLI_MagicSet_FlagWiring/equivalence_method_calls).
	//
	// Concretely: an entry in `sizeHints[pred]` where `pred` is also an
	// IDB head almost always refers to a shadowed base relation, not a
	// reliable IDB cardinality estimate. Phase A only consumes hints for
	// IDBs that are NOT also base-shadowed; reliable IDB estimates come
	// from `eval.EstimateNonRecursiveIDBSizes`, which runs *after*
	// planning today. Re-running magic-set after IDB estimation (so
	// BackwardTracker queries with subclass-only `isSink_<X>` predicates
	// can benefit) is tracked as the Phase A.1 follow-up.
	idbOnlyHints := make(map[string]int, len(sizeHints))
	for k, v := range sizeHints {
		if !idb[k] {
			// Pure base relation hint — irrelevant to InferRuleBindings
			// (which only looks up IDB names) but harmless to include.
			idbOnlyHints[k] = v
		}
		// If k is in idb, the hint is a base-shadowed lookup; skip it.
	}
	ruleBindings := InferRuleBindings(prog, idb, idbOnlyHints)
	// Drop rule bindings that would lead the magic-set transform to
	// emit an unsafe propagation head. Two failure modes are guarded:
	//
	//   1. Direct: a rule body contains `pred(...)` with a wildcard or
	//      `_` in one of the bound positions. Propagation copies that
	//      arg into `magic_pred`'s head — unsafe.
	//   2. Transitive: a rule with `pred(...)` in the body propagates
	//      a binding to some downstream predicate `Q`, and a rule body
	//      containing `Q(...)` then has a wildcard in the propagated
	//      position.
	//
	// We compute the full transitive binding closure first (using the
	// existing propagateBindings pass) and reject bindings whose
	// closure intersects any wildcard-bearing body literal. Issue #121.
	if len(ruleBindings) > 0 {
		ruleBindings = filterRuleBindingsAvoidingWildcards(prog, ruleBindings)
	}
	var ruleSeeds []datalog.Rule
	if len(ruleBindings) > 0 {
		// Use the same IDB-shadow-filtered hints that produced
		// `ruleBindings` so seed-rule grounding decisions stay
		// consistent with the binding inference (no soundness bug
		// either way today, since the filtered preds wouldn't have
		// produced bindings, but consistency makes future
		// refactoring less error-prone).
		ruleSeeds = BuildRuleSeedRules(prog, idb, idbOnlyHints, ruleBindings)
		// Merge rule-derived bindings into the inference's binding map
		// so that MagicSetTransform sees them and rewrites the
		// corresponding rule bodies to consume `magic_<pred>` (rather
		// than emitting only-seed rules that no body literal references).
		// First-occurrence-wins: never overwrite a query-body binding.
		if inf.Bindings == nil {
			inf.Bindings = make(map[string][]int)
		}
		for pred, cols := range ruleBindings {
			if _, exists := inf.Bindings[pred]; !exists {
				inf.Bindings[pred] = cols
			}
		}
		inf.SeedRules = append(inf.SeedRules, ruleSeeds...)
	}

	if len(inf.Bindings) == 0 {
		ep, errs := Plan(prog, sizeHints)
		return ep, inf, errs
	}

	// Arity guard (MINOR 5): ensure each seed-rule head matches the binding
	// arity declared for its predicate. A mismatch means the inference and
	// the transform disagree about the magic-pred shape; prefer the safe
	// plain plan over a broken augmented program.
	//
	// NOTE (#124 follow-up): this guard IS reachable from real input. The
	// inference loop in InferQueryBindings records bindings[pred] only on
	// the first occurrence of pred in the query body (`if !exists`), but
	// appends a fresh seed rule for every occurrence using the *current*
	// iteration's len(boundCols). When the same IDB pred appears twice
	// with different bound-column counts (e.g. body `P(1,y), P(2,3)` over
	// `P/2`), the second seed rule's head arity disagrees with the
	// recorded binding arity. This guard catches that asymmetry. The
	// long-term fix likely belongs in InferQueryBindings (widen or skip
	// the second seed); until then strict mode surfaces the mismatch and
	// non-strict falls back to plain Plan with FallbackReason populated.
	// Test coverage: TestWithMagicSetAutoOpts_ArityMismatchSamePredDifferentArity.
	for _, sr := range inf.SeedRules {
		// magic_<pred> -> <pred>
		predName := sr.Head.Predicate
		const prefix = "magic_"
		if len(predName) <= len(prefix) || predName[:len(prefix)] != prefix {
			continue
		}
		basePred := predName[len(prefix):]
		want, ok := inf.Bindings[basePred]
		if !ok {
			continue
		}
		if len(sr.Head.Args) != len(want) {
			arityErr := fmt.Errorf("magic-set arity mismatch: seed-rule head %s/%d but binding declares %d positions",
				sr.Head.Predicate, len(sr.Head.Args), len(want))
			if opts.Strict {
				return nil, QueryBindingInference{}, []error{arityErr}
			}
			ep, errs := Plan(prog, sizeHints)
			return ep, QueryBindingInference{Fallback: true, FallbackReason: arityErr}, errs
		}
	}

	transformed := MagicSetTransform(prog, inf.Bindings)
	// Append the seed rules so magic_<pred> has a non-empty extension.
	if len(inf.SeedRules) > 0 {
		augmentedRules := make([]datalog.Rule, 0, len(transformed.Rules)+len(inf.SeedRules))
		augmentedRules = append(augmentedRules, transformed.Rules...)
		augmentedRules = append(augmentedRules, inf.SeedRules...)
		transformed = &datalog.Program{
			Rules: augmentedRules,
			Query: transformed.Query,
		}
	}
	ep, errs := Plan(transformed, sizeHints)
	// Plan-error fallback (MAJOR 3 + transform-soundness safety net):
	// if the augmented program fails to plan for any reason — unstratifiable
	// (e.g. seed bodies copying a preceding `not Bar(m)` that creates a new
	// negation edge into a recursive component) or unsafe (e.g. seed-head
	// wildcards leaked from the transform) — fall back to plain Plan rather
	// than surfacing the regression to the caller. The transform is opt-in
	// (--magic-sets); silent fallback to a known-good plan is the right
	// default until transform soundness is fully proven on real workloads.
	//
	// Strict mode (issue #112) surfaces these errors instead, so CI / tests
	// can detect transform regressions that would otherwise be invisible.
	if len(errs) > 0 {
		if opts.Strict {
			return nil, QueryBindingInference{}, errs
		}
		ep2, errs2 := Plan(prog, sizeHints)
		return ep2, QueryBindingInference{Fallback: true, FallbackReason: errs[0]}, errs2
	}
	return ep, inf, errs
}

// (containsUnstratifiable removed: superseded by the broader plan-error
// fallback above; we now treat any planning error from the augmented program
// as "fall back to plain Plan." Kept the import of strings out of this file
// since the helper is no longer needed.)

func isConstTerm(t datalog.Term) bool {
	switch t.(type) {
	case datalog.IntConst, datalog.StringConst:
		return true
	}
	return false
}

func hasConstTerm(args []datalog.Term) bool {
	for _, a := range args {
		if isConstTerm(a) {
			return true
		}
	}
	return false
}
