// Package plan — query-binding inference and seed-rule generation for magic sets.
//
// The MagicSetTransform itself only knows how to *propagate* bindings through
// rule bodies once told which top-level head positions are bound. Production
// queries need two extra pieces:
//
//  1. **Binding inference.** Walk the desugared query body and figure out which
//     argument positions of each IDB-predicate literal are bound at query time.
//     A position is bound if its term is a constant, a wildcard variable equated
//     to a constant by a `=` comparison in the same query body, or a variable
//     that is already bound by a preceding base-relation literal carrying a
//     constant in the corresponding column.
//
//  2. **Seed rules.** The magic_<pred>(...) propagation rules generated by the
//     transform have no base case unless the EDB is seeded. We generate a seed
//     rule for each query body literal of the form
//     magic_<pred>(args_at_bound_positions) :- <preceding query body lits>.
//     The preceding-literal context is what gives us the bound values at runtime.
//
// Conservative-by-design: if we cannot determine that a position is bound,
// we omit it from the binding set. An empty binding set causes WithMagicSet
// to fall through to plain Plan, which is the safe baseline.
package plan

import (
	"github.com/Gjdoalfnrxu/tsq/ql/datalog"
)

// QueryBindingInference is the result of analysing a query body.
type QueryBindingInference struct {
	// Bindings maps IDB predicate name → bound argument positions, as
	// expected by MagicSetTransform.
	Bindings map[string][]int
	// SeedRules are zero- or N-body rules that derive magic_<pred> facts at
	// evaluation time using the query body's own context.
	SeedRules []datalog.Rule
}

// InferQueryBindings analyses prog.Query and returns the binding map and the
// seed rules needed to make the magic-set rewrite produce results.
//
// idbPreds is the set of predicate names that appear as rule heads in the
// program (i.e. derived predicates eligible for magic-set rewriting).
//
// Returns an empty inference (nil maps/slices) if the query has no body or
// no inferable bindings — caller should then skip the magic-set transform.
func InferQueryBindings(prog *datalog.Program, idbPreds map[string]bool) QueryBindingInference {
	if prog == nil || prog.Query == nil || len(prog.Query.Body) == 0 {
		return QueryBindingInference{}
	}

	// First pass: collect variables that are equality-constrained to constants
	// in the query body. These are "bound by query" — when their host literal
	// is evaluated, the variable will have a known value.
	constBoundVars := make(map[string]bool)
	varToConst := make(map[string]datalog.Term)
	for _, lit := range prog.Query.Body {
		if lit.Cmp == nil || lit.Cmp.Op != "=" {
			continue
		}
		// var = const  or  const = var
		if v, ok := lit.Cmp.Left.(datalog.Var); ok {
			if isConstTerm(lit.Cmp.Right) {
				constBoundVars[v.Name] = true
				varToConst[v.Name] = lit.Cmp.Right
			}
		}
		if v, ok := lit.Cmp.Right.(datalog.Var); ok {
			if isConstTerm(lit.Cmp.Left) {
				constBoundVars[v.Name] = true
				varToConst[v.Name] = lit.Cmp.Left
			}
		}
	}

	// Second pass: track variables bound by *preceding* base-relation
	// (non-IDB) literals. Positional binding from preceding IDB literals is
	// NOT used because (a) it is almost always trivially true (any second IDB
	// literal sharing a var with the first has a "bound" first column), which
	// makes magic-set rewriting fire on queries it does not actually help, and
	// (b) it can introduce IDB→IDB seed-rule dependencies that perturb
	// stratification. v1 restricts itself to true ground-by-query bindings:
	//   - constant terms in the IDB literal itself,
	//   - vars equality-constrained to a constant in the query body,
	//   - vars ground by a preceding base-relation atom that itself contains
	//     a constant in the same column (proxy: the variable shares an atom
	//     with a constant in a preceding base literal).
	baseBoundVars := make(map[string]bool)

	bindings := make(map[string][]int)
	var seedRules []datalog.Rule

	for i, lit := range prog.Query.Body {
		// Skip non-positive / comparison / aggregate literals — they don't
		// contribute new IDB-position bindings.
		if lit.Cmp != nil || lit.Agg != nil || !lit.Positive {
			continue
		}
		pred := lit.Atom.Predicate
		if !idbPreds[pred] {
			// Not an IDB pred — it can ground variables for subsequent literals,
			// but only those vars that co-occur with a constant in this base
			// atom (i.e. the atom acts as a constant-bound lookup). This keeps
			// the inference conservative: a free base atom over a variable
			// alone does not "bind" anything in the magic-set sense.
			if hasConstTerm(lit.Atom.Args) {
				for _, arg := range lit.Atom.Args {
					if v, ok := arg.(datalog.Var); ok && v.Name != "_" {
						baseBoundVars[v.Name] = true
					}
				}
			}
			continue
		}

		// Determine which argument positions of this IDB literal are bound at
		// query-evaluation time. A position is bound if:
		//   - it's a constant term, OR
		//   - it's a variable that's in constBoundVars (= const constraint), OR
		//   - it's a variable that's positionally-bound by a preceding literal.
		var boundCols []int
		for ai, arg := range lit.Atom.Args {
			switch a := arg.(type) {
			case datalog.IntConst, datalog.StringConst:
				boundCols = append(boundCols, ai)
			case datalog.Var:
				if a.Name == "_" {
					continue
				}
				if constBoundVars[a.Name] || baseBoundVars[a.Name] {
					boundCols = append(boundCols, ai)
				}
			}
		}

		if len(boundCols) > 0 {
			// Merge with existing bindings for this predicate. v1 takes the
			// first occurrence's bindings (a conservative non-intersect choice).
			// If the same pred recurs with a different binding shape we keep
			// the first; the equivalence tests guarantee correctness either way.
			if _, exists := bindings[pred]; !exists {
				bindings[pred] = boundCols
			}

			// Build the seed rule:
			//   magic_<pred>(args_at_bound_positions) :- <preceding query body literals>.
			// "Preceding" means literals 0..i-1 — they provide the binding
			// context (constraints + base lookups) needed to ground the bound vars.
			seedHeadArgs := make([]datalog.Term, len(boundCols))
			for k, col := range boundCols {
				arg := lit.Atom.Args[col]
				// If the arg is a variable that has a known constant value
				// (via `var = const` in the query body), substitute the
				// constant directly. This lets us emit a fact-shaped seed
				// (no body needed for that var) instead of relying on the
				// evaluator to derive the binding from a bare comparison.
				if v, ok := arg.(datalog.Var); ok {
					if c, has := varToConst[v.Name]; has {
						arg = c
					}
				}
				seedHeadArgs[k] = arg
			}
			seedHead := datalog.Atom{
				Predicate: magicName(pred),
				Args:      seedHeadArgs,
			}
			// Body = all preceding query literals (j < i). Trailing
			// `var = const` comparisons are unnecessary because the constant
			// has already been substituted into the seed head above.
			// Aggregates are skipped — they can't appear at this scope cleanly.
			var seedBody []datalog.Literal
			for j, prev := range prog.Query.Body {
				if j >= i || prev.Agg != nil {
					continue
				}
				seedBody = append(seedBody, prev)
			}

			// Safety check: every variable in the seed head must appear in
			// the seed body (or be a constant). isSafe handles that.
			if isSafe(seedHead, seedBody) {
				seedRules = append(seedRules, datalog.Rule{
					Head: seedHead,
					Body: seedBody,
				})
			} else {
				// Couldn't generate a safe seed — drop the binding to avoid
				// rewriting a rule whose magic predicate will never have any
				// tuples (which would yield an empty result set).
				delete(bindings, pred)
			}
		}

	}

	if len(bindings) == 0 {
		return QueryBindingInference{}
	}
	return QueryBindingInference{
		Bindings:  bindings,
		SeedRules: seedRules,
	}
}

// IDBPredicates returns the set of predicate names that appear as rule heads.
func IDBPredicates(prog *datalog.Program) map[string]bool {
	idb := make(map[string]bool)
	if prog == nil {
		return idb
	}
	for _, r := range prog.Rules {
		idb[r.Head.Predicate] = true
	}
	return idb
}

// WithMagicSetAuto infers query bindings, applies the magic-set transform
// when bindings are inferable, generates the seed rules required to make the
// magic predicates produce tuples at evaluation time, and plans the result.
//
// Returns the plan, the inference (so callers can log what fired), and any
// planning errors. If no bindings are inferable, falls back to plain Plan and
// returns an inference with empty Bindings.
func WithMagicSetAuto(prog *datalog.Program, sizeHints map[string]int) (*ExecutionPlan, QueryBindingInference, []error) {
	idb := IDBPredicates(prog)
	inf := InferQueryBindings(prog, idb)
	if len(inf.Bindings) == 0 {
		ep, errs := Plan(prog, sizeHints)
		return ep, inf, errs
	}

	// Arity guard (MINOR 5): ensure each seed-rule head matches the binding
	// arity declared for its predicate. A mismatch means the inference and
	// the transform disagree about the magic-pred shape; prefer the safe
	// plain plan over a broken augmented program.
	for _, sr := range inf.SeedRules {
		// magic_<pred> -> <pred>
		predName := sr.Head.Predicate
		const prefix = "magic_"
		if len(predName) <= len(prefix) || predName[:len(prefix)] != prefix {
			continue
		}
		basePred := predName[len(prefix):]
		want, ok := inf.Bindings[basePred]
		if !ok {
			continue
		}
		if len(sr.Head.Args) != len(want) {
			ep, errs := Plan(prog, sizeHints)
			return ep, QueryBindingInference{}, errs
		}
	}

	transformed := MagicSetTransform(prog, inf.Bindings)
	// Append the seed rules so magic_<pred> has a non-empty extension.
	if len(inf.SeedRules) > 0 {
		augmentedRules := make([]datalog.Rule, 0, len(transformed.Rules)+len(inf.SeedRules))
		augmentedRules = append(augmentedRules, transformed.Rules...)
		augmentedRules = append(augmentedRules, inf.SeedRules...)
		transformed = &datalog.Program{
			Rules: augmentedRules,
			Query: transformed.Query,
		}
	}
	ep, errs := Plan(transformed, sizeHints)
	// Plan-error fallback (MAJOR 3 + transform-soundness safety net):
	// if the augmented program fails to plan for any reason — unstratifiable
	// (e.g. seed bodies copying a preceding `not Bar(m)` that creates a new
	// negation edge into a recursive component) or unsafe (e.g. seed-head
	// wildcards leaked from the transform) — fall back to plain Plan rather
	// than surfacing the regression to the caller. The transform is opt-in
	// (--magic-sets); silent fallback to a known-good plan is the right
	// default until transform soundness is fully proven on real workloads.
	if len(errs) > 0 {
		ep2, errs2 := Plan(prog, sizeHints)
		return ep2, QueryBindingInference{}, errs2
	}
	return ep, inf, errs
}

// (containsUnstratifiable removed: superseded by the broader plan-error
// fallback above; we now treat any planning error from the augmented program
// as "fall back to plain Plan." Kept the import of strings out of this file
// since the helper is no longer needed.)

func isConstTerm(t datalog.Term) bool {
	switch t.(type) {
	case datalog.IntConst, datalog.StringConst:
		return true
	}
	return false
}

func hasConstTerm(args []datalog.Term) bool {
	for _, a := range args {
		if isConstTerm(a) {
			return true
		}
	}
	return false
}
